### ISSUE TITLE
render MOM6 example with correct mesh geometry

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-example-notebooks#11]
Currently the MOM6 example by @gustavo-marques shows maps like this

![image](https://user-images.githubusercontent.com/1197350/44826994-139e5380-abdf-11e8-8371-52293004987c.png)

@adcroft correctly pointed out that these are not the correct coordinates. We should be creating an irregular QuadMesh. This is apparently possible with holoviews / geoviews
- http://holoviews.org/reference/elements/bokeh/QuadMesh.html
- http://geo.holoviews.org/gallery/bokeh/xarray_quadmesh.html

This example from geoviews in particular looks like what we want.
![image](https://user-images.githubusercontent.com/1197350/44827045-506a4a80-abdf-11e8-8b01-f1c85e7ce3ab.png)

However, the current MOM6 zarr dataset doesn't even have the geographic coordinates in it.
```
<xarray.Dataset>
Dimensions:     (Time: 7300, nv: 2, xh: 540, xq: 540, yh: 458, yq: 458)
Coordinates:
  * Time        (Time) int64 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 ...
  * nv          (nv) float64 1.0 2.0
  * xh          (xh) float64 -286.7 -286.0 -285.3 -284.7 -284.0 -283.3 ...
  * xq          (xq) float64 -286.3 -285.7 -285.0 -284.3 -283.7 -283.0 ...
  * yh          (yh) float64 -79.2 -79.08 -78.95 -78.82 -78.69 -78.56 -78.43 ...
  * yq          (yq) float64 -79.14 -79.01 -78.89 -78.76 -78.63 -78.49 ...
Data variables:
    SSH         (Time, yh, xh) float32 dask.array<shape=(7300, 458, 540), chunksize=(365, 458, 540)>
    SSS         (Time, yh, xh) float32 dask.array<shape=(7300, 458, 540), chunksize=(365, 458, 540)>
    SST         (Time, yh, xh) float32 dask.array<shape=(7300, 458, 540), chunksize=(365, 458, 540)>
    Time_bnds   (Time, nv) float64 dask.array<shape=(7300, 2), chunksize=(7300, 2)>
    average_DT  (Time) float64 dask.array<shape=(7300,), chunksize=(7300,)>
    average_T1  (Time) float64 dask.array<shape=(7300,), chunksize=(7300,)>
    average_T2  (Time) float64 dask.array<shape=(7300,), chunksize=(7300,)>
    ePBL_h_ML   (Time, yh, xh) float32 dask.array<shape=(7300, 458, 540), chunksize=(365, 458, 540)>
Attributes:
    associated_files:  area_t: g.c2b6.GNYF.T62_t061.control.004.mom6.static.nc
    filename:          g.c2b6.GNYF.T62_t061.control.004.mom6.sfc.day._0001_00...
    grid_tile:         N/A
    grid_type:         regular
    title:             MOM6 g.c2b6.GNYF.T62_t061.control.004 Experiment
```

So before we can fix the plot, we need to fix the data. @gustavo-marques, could you add the lat / lon coordinates? You can just upload the directories to the existing zarr group and it should "just work". (A lot easier than adding a variable to a netCDF file!)

**Comment by adcroft** [comment]
The absence of the 2D coordinates and mesh data in the output files is very much an annoyance. It is possible for users to specify to add this data but they have to do so explicitly for each and every file which is very cumbersome. However, we do normally write the 2D coordinates and mesh to a "static" data file (in the above example this is referred to by the `associated_files` attribute). The fragile part of this is that the data and coordinates are in separate files and prone to be disconnected or mixed up.

I totally agree that we need to fix the data first. The short-term solution is to add the 2D mesh data to the same files using the cumbersome approach. In the longer term, I think we need a way to indicate within the netCDF file which variables are the associated mesh coordinates. Currently the CF convention has an attribute "coordinates" which is explicitly for cell center [coordinates](http://cfconventions.org/cf-conventions/cf-conventions.html#coordinate-system). I think we should propose to CF an attribute such as "mesh_coordinates" to indicate which data defines the grid for each variable. (This proposal is off thread so I will take it up elsewhere).

@gustavo-marques How hard would it be for you to add geolon, geolat, geolon_c, geolat_c to each of the files in the diag_table that you use for this example?

**Comment by gustavo-marques** [comment]
Thanks @adcroft  for catching this and thanks @rabernat for proposing a solution to it. I will look into fix the problem (hopefully today) by either 1) uploading the directories to the existing zarr group; or 2) adding the lat/lon arrays into the netCDF files.

**Comment by gustavo-marques** [comment]
I've 2D added lon/lat arrays, but open_zarr interprets them as variables:

![image](https://user-images.githubusercontent.com/11339137/45002092-5621b080-af90-11e8-8b68-eb2f1fe91d96.png)

I tried append/concat, but this is still an open [issue](https://github.com/pydata/xarray/issues/2022). @rabernat, any ideas?

Another approach is to follow @adcroft 's suggestion, but for that I will have to re-run the model since the original data has been purged.

**Comment by rabernat** [comment]
@gustavo-marques: I guess you have resolved this?

When I open `'pangeo-data/MOM6.cesm/'`, I now see the correct coordinates. However, the example notebook is now broken because it points to `'pangeo-data/MOM6.CESM/'`, which no longer exists.

FYI, one work around would have been to directly edit the `.zattrs` file to specify what the coordinates are:
https://storage.googleapis.com/pangeo-data/MOM6.cesm/.zattrs

**Comment by rabernat** [comment]
Actually, there is a problem with the new dataset:
```
<xarray.Dataset>
Dimensions:       (nv: 2, time: 60, xh: 540, xq: 540, yh: 458, yq: 458, z_i: 35, z_l: 34)
Coordinates:
    geolat        (time, yh, xh) float64 dask.array<shape=(60, 458, 540), chunksize=(1, 458, 540)>
    geolat_u      (time, yh, xq) float64 dask.array<shape=(60, 458, 540), chunksize=(1, 458, 540)>
    geolat_v      (time, yq, xh) float64 dask.array<shape=(60, 458, 540), chunksize=(1, 458, 540)>
    geolon        (time, yh, xh) float64 dask.array<shape=(60, 458, 540), chunksize=(1, 458, 540)>
    geolon_u      (time, yh, xq) float64 dask.array<shape=(60, 458, 540), chunksize=(1, 458, 540)>
    geolon_v      (time, yq, xh) float64 dask.array<shape=(60, 458, 540), chunksize=(1, 458, 540)>
  * nv            (nv) float64 1.0 2.0
  * time          (time) float64 15.5 45.0 74.5 105.0 135.5 166.0 196.5 ...
  * xh            (xh) float64 -286.7 -286.0 -285.3 -284.7 -284.0 -283.3 ...
  * xq            (xq) float64 -286.3 -285.7 -285.0 -284.3 -283.7 -283.0 ...
  * yh            (yh) float64 -79.2 -79.08 -78.95 -78.82 -78.69 -78.56 ...
  * yq            (yq) float64 -79.14 -79.01 -78.89 -78.76 -78.63 -78.49 ...
  * z_i           (z_i) float64 0.0 5.0 15.0 25.0 40.0 62.5 87.5 112.5 137.5 ...
  * z_l           (z_l) float64 2.5 10.0 20.0 32.5 51.25 75.0 100.0 125.0 ...
```

The geolon coordinates should not have a time dimension!

**Comment by rabernat** [comment]
With your new data, this works:

```python
qm = hv.QuadMesh((ds.geolon[0].values, ds.geolat[0].values, ds.SST[0].values))
qm
```
 
![bokeh_plot](https://user-images.githubusercontent.com/1197350/45569096-8426b080-b82c-11e8-805a-95b434b83898.png)

**Comment by adcroft** [comment]
We've recently fixed the values of longitude in the output along the top edge - not sure if that's included here, @gustavo-marques ?

Ideally the dimensions in the dataset would be xq=xh+1, yq=yh+1 but to get this the model needs to be run the model in a different mode. If you zoom in to (100W,90N) I expect there to be a gap? If you plotted `ds.SST[0].values[1:,1:]` then the gap should disappear? At least, based in pcolormesh behavior.
