### ISSUE TITLE
error in SOSE_tracer_budgets.ipynb

### ISSUE THREAD

**Issue by weiweiutd** [pangeo-data/pangeo-example-notebooks#36]
gateway = Gateway() from the first cell has incurred the error message (see below). Could anyone help with this? Thank you!
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-86a10c36346c> in <module>
      2 from dask_gateway import Gateway
      3 
----> 4 gateway = Gateway()
      5 cluster = gateway.new_cluster()
      6 cluster.scale(30)

~/opt/anaconda3/lib/python3.7/site-packages/dask_gateway/client.py in __init__(self, address, proxy_address, auth, asynchronous, loop)
    266         if address is None:
    267             raise ValueError(
--> 268                 "No dask-gateway address provided or found in configuration"
    269             )
    270         address = address.rstrip("/")

ValueError: No dask-gateway address provided or found in configuration

**Comment by TomAugspurger** [comment]
Hopefully https://github.com/pangeo-data/pangeo-example-notebooks/pull/37 fixes this. Need to verify that though.

**Comment by TomAugspurger** [comment]
Seems to be working after #37 

At some point we probably want this to use https://github.com/pangeo-gallery/default-binder, but that'll take a bit of time.
